### ISSUE TITLE
This does not work on Node.js 4.2.0? What gives?

### ISSUE THREAD

**Issue by dougwilson** [qarl/lumetools#1]

**Comment by qarl** [comment]
it's a shame you're acting like this.  regardless, i wish you well.

**Comment by dougwilson** [comment]
Yes, I agree, it is a shame you are acting like this. I really hope you feel better soon.

Let me know ASAP when you get Node.js 4.2.0 support added here. I won't try figuring out why it doesn't work or offer up a pull request, only feel entitled that you should serve my needs, even though other users who couldn't use 4.2.0 were perfectly willing to upgrade Node.js and the issue was open for months. Please do get right on this issue, you owe me.

**Comment by dougwilson** [comment]
Actually, there is something you can do. If you discover that many of your users are suffering from this problem, you could find a workaround (perhaps use a different timeout mechanism, or some such.) This is common in software development; I'm surprised you're unaware of it, @qarl. You're clearly an awful software developer, not knowing about this. Shame on you for not making this work on Node.js 4.2.0. SHAME.

**Comment by dougwilson** [comment]
I think it's a shame my first interaction with you was that you come into a repository I oversee, and acted completely entitled to get what you wanted done, without adding any value what-so-ever. Even your argument that all those people had issues and I ignored them is bullshit, in my opinion. I don't see a single person in that thread saying they had to get it fixed and working on 4.2.0, only that they were having the issue and then confirming that they upgraded their Node.js and everything was working. Because people continue to find themselves on Node.js 4.2.0 and posted in there over and over, we look the issue so people can find it on the Internet, read the thread, and understand the resolution is to upgrade the version of Node.js

> But I thought it was important to speak-up and say "this problem still exists."

You thought wrong.

> But since the comments are locked on that issue, I was forced to create a new issue.

That is correct. Here's the thing: comments on an old, closed issue is usually never seen by anyone looking at the repository. One of the reasons we lock issue is to force people to open new issues so they are actually seen, and ideally, not spam all the old users in that thread and hopefully encourage people to help bring up information to move the issue forward. GitHub  has heard complaints from repository owners that "me too" issues and comments are absolutely useless and unhelpful and so added the "emotions" pattern now instead, so users can "me too" in silence by thumbs-uping an issue, not making comments that do not move anything forward.

> And I'm somewhat curious as to why you'd lock the comments on an unsolved problem. (Never mind closing it. Presumably you have a different definition of "closed" than I do.)

This comment right here is what sent me off. That comment is a super dickish comment, fucking questioning how we rung repositories like you know better. This comment is where our interaction went south on my end, I'm sorry to tell you.

Please never ever step into any module I have touched ever again. If I have already turned you off to that anyway, that's A-OK since I do not want to see your name in anything. I have blocked your account on GitHub, whatever that does.

> Perhaps if you hadn't locked the comments on the other issue, someone would have told you about this before now. Again, I remain curious about that decision.

What a fucking disk comment, you dick. That issue was unlocked for 3 months and was not the only issue about this topic, but obviously you already know all this, because you're better than me. I am but a child, and you have chased me off your lawn.

**Comment by qarl** [comment]
> I am but a child

Yes, you have provided ample evidence.  Take care.

**Comment by dougwilson** [comment]
> Yes, you have provided ample evidence. Take care.

Whew, I was really worried you would not see it, but I'm really glad you have come to this realization. The world will be a much better place now.

**Comment by dougwilson** [comment]
Oops, didn't mean to comment here.

**Comment by dougwilson** [comment]
Oops, didn't mean to comment here.

**Comment by dougwilson** [comment]
Oops, didn't mean to comment here.

**Comment by dougwilson** [comment]
Oops, didn't mean to comment here.

**Comment by dougwilson** [comment]
Oops, didn't mean to comment here.

**Comment by dougwilson** [comment]
Oops, didn't mean to comment here.

**Comment by dougwilson** [comment]
Oops, didn't mean to comment here.

**Comment by dougwilson** [comment]
Oops, didn't mean to comment here.

**Comment by dougwilson** [comment]
Oops, didn't mean to comment here.

**Comment by dougwilson** [comment]
Oops, didn't mean to comment here.

**Comment by dougwilson** [comment]
Oops, didn't mean to comment here.

**Comment by dougwilson** [comment]
Oops, didn't mean to comment here.

**Comment by dougwilson** [comment]
Oops, didn't mean to comment here.

**Comment by dougwilson** [comment]
Oops, didn't mean to comment here.

**Comment by dougwilson** [comment]
Oops, didn't mean to comment here.

**Comment by dougwilson** [comment]
Oops, didn't mean to comment here.

**Comment by dougwilson** [comment]
Oops, didn't mean to comment here.

**Comment by dougwilson** [comment]
Oops, didn't mean to comment here.

**Comment by dougwilson** [comment]
> Oops, didn't mean to comment here.

I'm not sure why Chrome just freaked out, and that wasn't even supposed to be for this window, it was for a IRC room.
